#!/bin/bash
set -euo pipefail
go run ./cmd/maze&

cat <<-EOF | osascript
tell application "System Events"
	repeat until window "Bedrock Pruner" of process "maze" exists
	end repeat

	tell process "maze"
		-- activate
		set frontmost to true
		-- perform action "AXRaise" of window 1
	end tell
end tell
EOF
